/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./components/AboutDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ProteinModificationDetailsDialog: typeof import('./components/modifications/ProteinModificationDetailsDialog.vue')['default']
    ProteinModificationsDataTable: typeof import('./components/modifications/ProteinModificationsDataTable.vue')['default']
    ProteinModificationsFilters: typeof import('./components/modifications/ProteinModificationsFilters.vue')['default']
    ProteinModificationsTable: typeof import('./components/modifications/ProteinModificationsTable.vue')['default']
    RangeSliderInput: typeof import('./components/common/RangeSliderInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmilesStatus: typeof import('./components/smiles/SmilesStatus.vue')['default']
    SmilesView: typeof import('./components/smiles/SmilesView.vue')['default']
  }
}
