name: generate-owl-tag-release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - main
      - test-tag
    paths:
      - 'PSI-MOD.obo'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Apply identifier conversion
        run: |
          pip install fastobo
          python src/scripts/convert.py --input "PSI-MOD.obo" --output "PSI-MOD-newstyle.obo"
      - name: Extract version from OBO
        run: |
          CV_VERSION=`grep data-version PSI-MOD-newstyle.obo | grep -oP "(\d+.\d+.\d+)"`
          echo CV_VERSION=${CV_VERSION}
          echo "CV_VERSION=${CV_VERSION}" >> $GITHUB_ENV
      - name: Generate OWL and Commit
        run: |
          docker pull obolibrary/robot:v1.8.1
          # Replace the imports of the UO and PATO ontology .obo files with the equivalent .owl files
          cp PSI-MOD-newstyle.obo tmp.obo
          export JAVA_TOOL_OPTIONS=-Xmx4G
          docker run --rm -v ${{ github.workspace }}:/work obolibrary/robot:v1.8.1 robot convert -vvv -i /work/tmp.obo -o /work/PSI-MOD.owl --format owl
          rm tmp.obo
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PSI_MS_CV_GITHUB_TOKEN }}
          commit-message: Update OWL file
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: update-owl-file
          delete-branch: true
          title: Update OWL file
          body: This automated PR updates the OWL file corresponding to the OBO file
      - name: Approve pull request
        if: (steps.cpr.outputs.pull-request-operation == 'created' ||	steps.cpr.outputs.pull-request-operation == 'updated')
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Merge pull request
        if: (steps.cpr.outputs.pull-request-operation == 'created' ||	steps.cpr.outputs.pull-request-operation == 'updated')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PSI_MS_CV_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
      - name: GitHub Tag
        id: new_tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.PSI_MS_CV_GITHUB_TOKEN }}
          pre_release_branches: test-tag
          custom_tag: ${{ env.CV_VERSION }}